### ISSUE TITLE
Maybe add browserify transform to package.json

### ISSUE THREAD

**Issue by jongacnik** [SilentCicero/yoyo-bootstrap#1]
When bundling this via browserify a [transform](https://github.com/substack/node-browserify#browserifytransform) is needed to handle the `@import` in less files. A plugin that works well for this is [node-lessify](https://www.npmjs.com/package/node-lessify). Adding the following to yoyo-bootstrap's package.json ensures everything is bundled up properly when requiring components:

```
"browserify": { 
  "transform": [ "node-lessify" ] 
}
```

Great work btw! This is awesome.🤘

**Comment by SilentCicero** [comment]
@jongacnik sorry for getting back so late, could you string this up in a PR. Looks simple enough. Just super busy on my end =D

**Comment by SilentCicero** [comment]
Maybe with a Readme header/body addition as well.

**Comment by jongacnik** [comment]
No problem, submitted → #2
